"""Generate coverage and check local documentation, CI coverage, and source review age."""
import argparse
from datetime import date
import json
from pathlib import Path
import re
import sys
from urllib.parse import unquote, urlsplit
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]


def manifests():
    return [json.loads(p.read_text(encoding="utf-8")) for p in sorted((ROOT / "labs").glob("*/lab.json"))]


def coverage():
    labs = manifests()
    lines = ["# Project coverage", "", "<!-- Generated by scripts/maintain_catalog.py --coverage. -->", "",
             "Catalog coverage describes implemented examples, not live sandbox verification.",
             "Times are planning estimates for a single project, not measured deployment durations.", "",
             "| Project | Areas | Local minutes | Azure minutes | Azure runner | Live verified |",
             "| --- | --- | ---: | ---: | --- | --- |"]
    for lab in labs:
        azure = lab["implementations"]["azure"]
        lines.append(f'| [{lab["title"]}](../labs/{lab["id"]}/) | {", ".join(lab["domains"])} | {lab["execution"]["local_minutes"]} | {azure["estimated_minutes"]} | {lab["execution"]["azure"]} | {"Yes — inspect record" if azure["status"] == "verified" else "No"} |')
    lines += ["", "## Required Azure services", "", "| Catalog service | Projects using it |", "| --- | --- |"]
    services = sorted({s for lab in labs for s in lab["implementations"]["azure"]["required_services"]})
    for service in services:
        names = [f'[{lab["id"]}](../labs/{lab["id"]}/)' for lab in labs if service in lab["implementations"]["azure"]["required_services"]]
        lines.append(f'| {service} | {", ".join(names)} |')
    lines += ["", "This is breadth across selected patterns, not a percentage of Azure functionality.",
              "Run one root at a time. Shared services appear in several rows but are not a composed deployment.", ""]
    return "\n".join(lines)


def source_profiles():
    return sorted((ROOT / "catalog/platforms").glob("*/*.json"))


def check_repository():
    failures = []
    expected = coverage()
    target = ROOT / "docs/coverage.md"
    if not target.exists() or target.read_text(encoding="utf-8") != expected:
        failures.append("docs/coverage.md is stale; regenerate from the catalog.")
    # Explicit content roots never traverse ignored v0.1 reference, artifacts or providers.
    documents = list(ROOT.glob("*.md"))
    for folder in ("docs", "labs", "templates"):
        documents += list((ROOT / folder).rglob("*.md"))
    for document in documents:
        content = document.read_text(encoding="utf-8")
        content = re.sub(r"```.*?```", "", content, flags=re.S)
        for match in re.finditer(r"\[[^\]\n]+\]\(([^)\s]+)\)", content):
            target_url = urlsplit(match[1].strip("<>"))
            if target_url.scheme or target_url.netloc or not target_url.path:
                continue
            path = (document.parent / unquote(target_url.path)).resolve()
            if not path.is_relative_to(ROOT) or not path.exists():
                failures.append(f"{document.relative_to(ROOT)}: missing/out-of-repo link {match[1]}")
    workflow = (ROOT / ".github/workflows/validate.yml").read_text(encoding="utf-8")
    roots = [p.parent.relative_to(ROOT).as_posix() for p in (ROOT / "modules").glob("*/versions.tf")]
    roots += [f'labs/{lab["id"]}/implementations/azure/terraform' for lab in manifests()]
    for root in roots:
        if f"- {root}\n" not in workflow:
            failures.append(f"Terraform CI matrix omits {root}")
    for lab in manifests():
        guide = ROOT / "labs" / lab["id"] / "README.md"
        if not guide.exists():
            failures.append(f'Missing project guide: {lab["id"]}')
        elif not all(f"## {section}" in guide.read_text() for section in ("Try", "Break", "Remix")):
            failures.append(f'Missing Try/Break/Remix sections: {lab["id"]}')
    return failures


def review_age(today=None):
    today = today or date.today()
    warnings = []
    for profile_path in source_profiles():
        profile = json.loads(profile_path.read_text(encoding="utf-8"))
        reviewed = profile.get("reviewed_on")
        if not reviewed:
            warnings.append(f"{profile_path.relative_to(ROOT)}: missing reviewed_on")
        elif (today - date.fromisoformat(reviewed)).days > 90:
            warnings.append(f"{profile_path.relative_to(ROOT)}: source review older than 90 days")
    return warnings


def check_sources():
    urls = set()
    for profile_path in source_profiles():
        profile = json.loads(profile_path.read_text(encoding="utf-8"))
        for source in profile.get("sources", []):
            url = source if isinstance(source, str) else source.get("url", "")
            if url.startswith("https://"):
                urls.add(url)
    failures = []
    for url in sorted(urls):
        try:
            # Bounded GET: some documentation sites reject HEAD.
            with urlopen(Request(url, headers={"User-Agent": "Cloud-Sandbox-source-check/0.3"}), timeout=15) as response:
                response.read(1024)
        except Exception as error:
            status = getattr(error, "code", "unavailable")
            message = f"{url}: {type(error).__name__} ({status}); review source access manually"
            if status in (403, 429):
                # Access denied/rate limiting does not establish that a public page is missing.
                print("REVIEW (source unverified): " + message, file=sys.stderr)
            else:
                failures.append(message)
    return failures


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--coverage", action="store_true", help="Print generated coverage Markdown")
    parser.add_argument("--check", action="store_true", help="Check repository contracts; no network")
    parser.add_argument("--sources", action="store_true", help="Check profile source URL availability; no semantic-change detection")
    args = parser.parse_args()
    if args.coverage:
        print(coverage(), end="")
    failures = check_repository() if args.check else []
    for warning in review_age() if args.check or args.sources else []:
        print("REVIEW: " + warning, file=sys.stderr)
    if args.sources:
        failures += check_sources()
    for failure in failures:
        print("FAIL: " + failure, file=sys.stderr)
    if failures:
        raise SystemExit(1)
    if args.check or args.sources:
        print("Requested maintenance checks completed. Review notices are not successful source verification.")
